CREATE DATABASE IF NOT EXISTS defaultdb;
USE defaultdb;

CREATE TABLE DANHMUCSANPHAM (
  ID_DM INT AUTO_INCREMENT PRIMARY KEY,
  MaDanhMuc VARCHAR(30) UNIQUE NOT NULL,
  TenDanhMuc VARCHAR(100) NOT NULL,
  MoTa VARCHAR(255),
  TrangThai VARCHAR(20) DEFAULT 'HoatDong',
  NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
  NgayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP,
  ThoiGianKhauHao INT DEFAULT 5,
  MaDot VARCHAR(50)
);

CREATE TABLE NHANVIEN (
  ID_NV INT AUTO_INCREMENT PRIMARY KEY,
  HoTen VARCHAR(100) NOT NULL,
  Email VARCHAR(100) UNIQUE,
  PhongBan VARCHAR(50),
  ChucVu VARCHAR(50),
  TrangThai VARCHAR(20) DEFAULT 'HoatDong'
);

CREATE TABLE TAIKHOAN (
  ID_TK INT AUTO_INCREMENT PRIMARY KEY,
  ID_NV INT NOT NULL UNIQUE,
  TenDangNhap VARCHAR(50) UNIQUE NOT NULL,
  MatKhau VARCHAR(255) NOT NULL,
  VaiTro VARCHAR(20) NOT NULL,
  TrangThai VARCHAR(20) DEFAULT 'HoatDong',
  NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (ID_NV) REFERENCES NHANVIEN(ID_NV)
);

CREATE TABLE THIETBI (
  ID_TB INT AUTO_INCREMENT PRIMARY KEY,
  ID_DM INT NOT NULL,
  TenThietBi VARCHAR(100) NOT NULL,
  Loai VARCHAR(50),
  SerialNumber VARCHAR(100) UNIQUE,
  NgayMua DATE,
  NguyenGia DECIMAL(15,2),
  TrangThai VARCHAR(20) DEFAULT 'SanSang',
  NgayCapPhat DATE,
  NgayThanhLy DATETIME,
  MaDotThanhLy VARCHAR(50),
  NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (ID_DM) REFERENCES DANHMUCSANPHAM(ID_DM)
);

CREATE TABLE AUDIT_LOG (
  ID_AL INT AUTO_INCREMENT PRIMARY KEY,
  ID_TK INT,
  MaTB INT,
  HanhDong VARCHAR(100),
  GiaTriCu VARCHAR(255),
  GiaTriMoi VARCHAR(255),
  NguoiSua VARCHAR(100),
  ThoiGian TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (ID_TK) REFERENCES TAIKHOAN(ID_TK),
  FOREIGN KEY (MaTB) REFERENCES THIETBI(ID_TB)
);

CREATE TABLE KHAUHAO (
  ID_KH INT AUTO_INCREMENT PRIMARY KEY,
  ID_TB INT NOT NULL UNIQUE,
  PhuongPhapTinh VARCHAR(50),
  ThoiGianSuDung INT,
  GiaTriThuHoi DECIMAL(15,2),
  GiaTriBanDau DECIMAL(15,2),
  NgayBatDau DATE,
  NgayKetThuc DATE,
  FOREIGN KEY (ID_TB) REFERENCES THIETBI(ID_TB)
);

CREATE TABLE LICHSUKHAUHAO (
  ID_LKH INT AUTO_INCREMENT PRIMARY KEY,
  ID_TB INT NOT NULL,
  Nam INT NOT NULL,
  Thang INT NOT NULL,
  GiaTriKhauHaoThang DECIMAL(15,2),
  GiaTriLuyKe DECIMAL(15,2),
  GiaTriConLai DECIMAL(15,2),
  NgayGhiNhan DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (ID_TB) REFERENCES THIETBI(ID_TB)
);

CREATE TABLE YEUCAU (
  ID_YC INT AUTO_INCREMENT PRIMARY KEY,
  ID_NV INT NOT NULL,
  LoaiYeuCau VARCHAR(50) NOT NULL,
  NgayGui DATETIME DEFAULT CURRENT_TIMESTAMP,
  TrangThaiDuyet VARCHAR(20) DEFAULT 'ChoDuyet',
  ID_TB INT,
  LyDo VARCHAR(255),
  NgayTraDuKien DATE,
  NgayDuyet DATETIME,
  NguoiDuyet VARCHAR(50),
  GhiChuDuyet VARCHAR(255),
  ID_CP INT NOT NULL,
  MaDot VARCHAR(50),
  FOREIGN KEY (ID_NV) REFERENCES NHANVIEN(ID_NV),
  FOREIGN KEY (ID_TB) REFERENCES THIETBI(ID_TB),
  FOREIGN KEY (ID_CP) REFERENCES LICHSUCAPPHAT(ID_CP)
);

CREATE TABLE LICHSUCAPPHAT (
  ID_CP INT AUTO_INCREMENT PRIMARY KEY,
  ID_TB INT NOT NULL,
  ID_NV INT NOT NULL,
  ID_YC INT,
  NgayCap DATETIME DEFAULT CURRENT_TIMESTAMP,
  NgayTraDuKien DATE,
  TrangThai VARCHAR(20),
  GhiChu VARCHAR(255),
  FOREIGN KEY (ID_TB) REFERENCES THIETBI(ID_TB),
  FOREIGN KEY (ID_NV) REFERENCES NHANVIEN(ID_NV),
  FOREIGN KEY (ID_YC) REFERENCES YEUCAU(ID_YC)
);

CREATE TABLE LICHSUTHUHOI (
  ID_TH INT AUTO_INCREMENT PRIMARY KEY,
  ID_CP INT NOT NULL,
  NgayThuHoi DATETIME DEFAULT CURRENT_TIMESTAMP,
  TinhTrang VARCHAR(255),
  ID_YC INT,
  GhiChu VARCHAR(255),
  FOREIGN KEY (ID_CP) REFERENCES LICHSUCAPPHAT(ID_CP),
  FOREIGN KEY (ID_YC) REFERENCES YEUCAU(ID_YC)
);
