USE defaultdb;

CREATE TABLE IF NOT EXISTS NHANVIEN (
    ID_NV INT PRIMARY KEY,
    HoTen VARCHAR(100) NOT NULL,
    Email VARCHAR(100) UNIQUE,
    VaiTro VARCHAR(50),
    TrangThai VARCHAR(20) DEFAULT 'HoatDong'
);

CREATE TABLE IF NOT EXISTS THIETBI (
    ID_TB INT PRIMARY KEY,
    TenThietBi VARCHAR(100) NOT NULL,
    Loai VARCHAR(50),
    SeriNumber VARCHAR(100) UNIQUE,
    NgayMua DATE,
    NguyenGia DECIMAL(15, 2),
    TrangThai VARCHAR(20) DEFAULT 'SanSang'
);


CREATE TABLE IF NOT EXISTS TAIKHOAN (
    ID_TK INT PRIMARY KEY AUTO_INCREMENT,
    ID_NV INT NOT NULL UNIQUE,
    Username VARCHAR(50) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_NV) REFERENCES NHANVIEN(ID_NV)
);

CREATE TABLE IF NOT EXISTS KHAUHAO (
    ID_KH INT PRIMARY KEY,
    ID_TB INT NOT NULL UNIQUE,
    PhuongPhapTinh VARCHAR(50),
    GiaTriConLai DECIMAL(15, 2),
    FOREIGN KEY (ID_TB) REFERENCES THIETBI(ID_TB)
);


CREATE TABLE IF NOT EXISTS YEUCAU (
    ID_YC INT PRIMARY KEY,
    ID_NV INT NOT NULL,
    LoaiYeuCau VARCHAR(50),
    NgayGui DATETIME DEFAULT CURRENT_TIMESTAMP,
    TrangThaiDuyet VARCHAR(20) DEFAULT 'ChoDuyet',
    FOREIGN KEY (ID_NV) REFERENCES NHANVIEN(ID_NV)
);

CREATE TABLE IF NOT EXISTS LICHSUCAPPHAT (
    ID_CP INT PRIMARY KEY,
    ID_TB INT NOT NULL,
    ID_NV INT NOT NULL,
    NgayCap DATETIME DEFAULT CURRENT_TIMESTAMP,
    TrangThai VARCHAR(20),
    FOREIGN KEY (ID_TB) REFERENCES THIETBI(ID_TB),
    FOREIGN KEY (ID_NV) REFERENCES NHANVIEN(ID_NV)
);

CREATE TABLE IF NOT EXISTS LICHSUTHUHOI (
    ID_TH INT PRIMARY KEY,
    ID_TB INT NOT NULL,
    NgayThuHoi DATETIME DEFAULT CURRENT_TIMESTAMP,
    TinhTrang VARCHAR(255),
    FOREIGN KEY (ID_TB) REFERENCES THIETBI(ID_TB)
);
