USE defaultdb;

CREATE TABLE IF NOT EXISTS NHANVIEN (
    ID_NV INT PRIMARY KEY AUTO_INCREMENT,         
    HoTen VARCHAR(100) NOT NULL,    
    Email VARCHAR(100) UNIQUE,      
    PhongBan VARCHAR(50),           
    ChucVu VARCHAR(50),             
    TrangThai VARCHAR(20) DEFAULT 'HoatDong' 
);


CREATE TABLE IF NOT EXISTS TAIKHOAN (
    ID_TK INT PRIMARY KEY AUTO_INCREMENT, 
    ID_NV INT NOT NULL UNIQUE,            
    TenDangNhap VARCHAR(50) NOT NULL UNIQUE,  
    MatKhau VARCHAR(255) NOT NULL,    
    VaiTro VARCHAR(20) NOT NULL,          
    TrangThai VARCHAR(20) DEFAULT 'HoatDong', 
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_TAIKHOAN_NHANVIEN FOREIGN KEY (ID_NV) REFERENCES NHANVIEN(ID_NV)
);

CREATE TABLE IF NOT EXISTS THIETBI (
    ID_TB INT PRIMARY KEY AUTO_INCREMENT,
    TenThietBi VARCHAR(100) NOT NULL,
    Loai VARCHAR(50),
    SeriNumber VARCHAR(100) UNIQUE,
    NgayMua DATE,
    NguyenGia DECIMAL(15, 2),
    TrangThai VARCHAR(20) DEFAULT 'SanSang'
);

CREATE TABLE IF NOT EXISTS DANHMUCSANPHAM (
    ID_DM INT PRIMARY KEY AUTO_INCREMENT,
    MaDanhMuc VARCHAR(30) NOT NULL UNIQUE,
    TenDanhMuc VARCHAR(100) NOT NULL,
    MoTa VARCHAR(255),
    TrangThai VARCHAR(20) NOT NULL DEFAULT 'HoatDong',
    NgayTao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);



CREATE TABLE KHAUHAO (
    ID_KH INT PRIMARY KEY AUTO_INCREMENT,
    ID_TB INT NOT NULL UNIQUE,
    PhuongPhapTinh VARCHAR(50),
    ThoiGianSuDung INT,
    GiaTriThuHoi DECIMAL(15, 2),
    GiaTriBanDau DECIMAL(15, 2),
    NgayBatDau DATE,
    FOREIGN KEY (ID_TB) REFERENCES THIETBI(ID_TB)
);


CREATE TABLE LICHSUKHAUAO (
    ID_LKH INT PRIMARY KEY AUTO_INCREMENT,
    ID_TB INT NOT NULL,
    Nam INT NOT NULL,
    Thang INT NOT NULL,
    GiaTriKhauHaoThang DECIMAL(15, 2), 
    GiaTriLuyKe DECIMAL(15, 2),        
    GiaTriConLai DECIMAL(15, 2),       
    NgayGhiNhan DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_TB) REFERENCES THIETBI(ID_TB)
);

CREATE TABLE IF NOT EXISTS YEUCAU (
    ID_YC INT PRIMARY KEY,
    ID_NV INT NOT NULL,
    ID_TB INT NULL,
    LoaiYeuCau VARCHAR(50) NOT NULL,
    LyDo VARCHAR(255),
    NgayTraDuKien DATE NULL,
    NgayGui DATETIME DEFAULT CURRENT_TIMESTAMP,
    TrangThaiDuyet VARCHAR(20) DEFAULT 'ChoDuyet',
    NgayDuyet DATETIME NULL,
    NguoiDuyet VARCHAR(50) NULL,
    GhiChuDuyet VARCHAR(255) NULL,
    ID_CP INT NULL,
    FOREIGN KEY (ID_NV) REFERENCES NHANVIEN(ID_NV),
    FOREIGN KEY (ID_TB) REFERENCES THIETBI(ID_TB)
);

CREATE TABLE IF NOT EXISTS LICHSUCAPPHAT (
    ID_CP INT PRIMARY KEY,
    ID_TB INT NOT NULL,
    ID_NV INT NOT NULL,
    ID_YC INT NULL,
    NgayCap DATETIME DEFAULT CURRENT_TIMESTAMP,
    NgayTraDuKien DATE NULL,
    TrangThai VARCHAR(20),
    GhiChu VARCHAR(255),
    FOREIGN KEY (ID_TB) REFERENCES THIETBI(ID_TB),
    FOREIGN KEY (ID_NV) REFERENCES NHANVIEN(ID_NV),
    FOREIGN KEY (ID_YC) REFERENCES YEUCAU(ID_YC)
);

CREATE TABLE IF NOT EXISTS LICHSUTHUHOI (
    ID_TH INT PRIMARY KEY,
    ID_CP INT NOT NULL, 
    ID_YC INT NULL,
    NgayThuHoi DATETIME DEFAULT CURRENT_TIMESTAMP,
    TinhTrang VARCHAR(255),
    GhiChu VARCHAR(255),
    CONSTRAINT FK_THUHOI_CAPPHAT FOREIGN KEY (ID_CP) REFERENCES LICHSUCAPPHAT(ID_CP),
    FOREIGN KEY (ID_YC) REFERENCES YEUCAU(ID_YC)
);
